import NavBar from "@/components/nav-bar";
import "/styles/globals.css";
import TopBar from "@/components/user-bar";
import Providers from "@/components/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopBar />
          {children}
          <NavBar />
        </Providers>
      </body>
    </html>
  );
}
